import { Key } from "@nut-tree-fork/nut-js";

/**
 * Maps client-sent key strings (lowercase) to nut-js Key enum.
 * Covers modifiers, navigation, function keys (F1–F12), and media keys.
 * Platform-specific behavior (e.g. media on Linux) can be documented in the wiki.
 */
export const KEY_MAP: Record<string, Key> = {
	// Modifiers
	shift: Key.LeftShift,
	control: Key.LeftControl,
	ctrl: Key.LeftControl,
	alt: Key.LeftAlt,
	meta: Key.LeftSuper,
	super: Key.LeftSuper,
	rightshift: Key.RightShift,
	rightcontrol: Key.RightControl,
	rightctrl: Key.RightControl,
	rightalt: Key.RightAlt,
	rightmeta: Key.RightSuper,
	rightsuper: Key.RightSuper,

	// Navigation & editing
	backspace: Key.Backspace,
	enter: Key.Enter,
	return: Key.Return,
	tab: Key.Tab,
	escape: Key.Escape,
	esc: Key.Escape,
	delete: Key.Delete,
	del: Key.Delete,
	insert: Key.Insert,
	ins: Key.Insert,
	home: Key.Home,
	end: Key.End,
	pageup: Key.PageUp,
	pgup: Key.PageUp,
	pagedown: Key.PageDown,
	pgdn: Key.PageDown,
	arrowup: Key.Up,
	arrowdown: Key.Down,
	arrowleft: Key.Left,
	arrowright: Key.Right,
	up: Key.Up,
	down: Key.Down,
	left: Key.Left,
	right: Key.Right,

	// Function keys
	f1: Key.F1,
	f2: Key.F2,
	f3: Key.F3,
	f4: Key.F4,
	f5: Key.F5,
	f6: Key.F6,
	f7: Key.F7,
	f8: Key.F8,
	f9: Key.F9,
	f10: Key.F10,
	f11: Key.F11,
	f12: Key.F12,
	f13: Key.F13,
	f14: Key.F14,
	f15: Key.F15,
	f16: Key.F16,
	f17: Key.F17,
	f18: Key.F18,
	f19: Key.F19,
	f20: Key.F20,
	f21: Key.F21,
	f22: Key.F22,
	f23: Key.F23,
	f24: Key.F24,

	// Special
	space: Key.Space,
	capslock: Key.CapsLock,
	numlock: Key.NumLock,
	scrolllock: Key.ScrollLock,
	pause: Key.Pause,
	printscreen: Key.Print,
	print: Key.Print,
	menu: Key.Menu,

	// Media (behavior may vary by OS)
	audiomute: Key.AudioMute,
	volumemute: Key.AudioMute,
	audiovoldown: Key.AudioVolDown,
	volumedown: Key.AudioVolDown,
	audiovolup: Key.AudioVolUp,
	volumeup: Key.AudioVolUp,
	audioplay: Key.AudioPlay,
	play: Key.AudioPlay,
	audiostop: Key.AudioStop,
	stop: Key.AudioStop,
	audiopause: Key.AudioPause,
	audioprev: Key.AudioPrev,
	previous: Key.AudioPrev,
	audionext: Key.AudioNext,
	next: Key.AudioNext,
	audiorewind: Key.AudioRewind,
	audioforward: Key.AudioForward,
};
